// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejsftzakfmlvvdyaojeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqc2Z0emFrZm1sdnZkeWFvamVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNDUzMTMsImV4cCI6MjA1MzkyMTMxM30.IiRePL2aYNte95uAtGeGtuH5pq9wrmSWIKCIKFjiSmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);